import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import Btn from "../components/Btn";
import { useState } from "react";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import { MdEmail } from "react-icons/md";

export default function Home() {
	const [lightMode, setLightMode] = useState("Dark");
	const [classMode, setClassMode] = useState("light body");

	function onBtnClick() {
		if (lightMode === "Light") {
			setLightMode("Dark");
			setClassMode(`light body`);
		} else {
			setLightMode("Light");
			setClassMode(`dark body`);
		}
	}
	return (
		<div className={classMode}>
			<div className={styles.container}>
				<Head>
					<title>Jayj Eaton Portfolio</title>
					<meta
						name="JayJ Eaton"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
					<link
						rel="preconnect"
						href="https://fonts.googleapis.com"
					/>
					<link
						rel="preconnect"
						href="https://fonts.gstatic.com"
						crossorigin
					/>
					<link
						href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@300;400&display=swap"
						rel="stylesheet"
					></link>
				</Head>
				<div className={styles.header}>
					<div className={styles.headerTitle}>
						<Link href="/">
							<h1 className={styles.title}>JJ Eaton</h1>
						</Link>
						<p className={styles.description}>
							&lt;Software Engineer/&gt;
						</p>
					</div>
					<Btn content={lightMode} onClick={onBtnClick} />
				</div>
				<hr className={styles.lineBreak} />
				<div className={styles.myLinks}>
					<a className="btnLink" href="https://github.com/oldbettie">
						<FaGithub />
					</a>
					<a className="btnLink" href="mailto: jayleaton@gmail.com">
						<MdEmail />
					</a>
					<a
						className="btnLink"
						href="https://www.linkedin.com/in/jayj-eaton/"
					>
						<FaLinkedin />
					</a>
				</div>
				{/* start of main content */}
				<div className={styles.mainContent}>
					<div className={styles.projects}>
						<div>
							<a href="https://oldbettie.github.io/tictactoe/">
								<Btn content="Project Zero" />
							</a>
						</div>
						<div>
							<a href="https://jayleaton-cookbook.herokuapp.com/">
								<Btn content="Cook-Book" />
							</a>
						</div>
						<div>
							<a href="https://project-2-5825e.web.app/">
								<Btn content="Pet-Pals" />
							</a>
						</div>
					</div>
					<div className={styles.skills}></div>
					<div className={styles.resume}></div>
					<div className={styles.about}></div>
				</div>
				{/* end of main content */}
				<p className={styles.createdBy}>Created with Next.js - 2022</p>
			</div>
		</div>
	);
}
